#! /bin/bash

WORKDIR="/data/work/osmosis/"

# postgresql database
DATABASE="osmosis"
USER="osmosis"
PASS="osmosis"

# programs
PREFIX=/usr/bin/time
OSMOSIS="$PREFIX osmosis -q"
OSMOSIS_DIR="/data/project/osmosis/osmosis-0.37/"
