#! /bin/bash

# paths
OSMOSIS_DIR="/data/project/osmosis/osmosis-0.39/"
WORKDIR="/data/work/osmosis/"
export JAVACMD_OPTIONS="-server -Xms1G -Xmx3G -XX:MaxPermSize=3G -Djava.io.tmpdir=/data/work/osmosis/tmp/"

# postgresql database
DATABASE="osmosis"
USER="osmosis"
PASS="osmosis"
BOUNDING_BOX="all"

# programs
PREFIX=/usr/bin/time
OSMOSIS="$PREFIX $OSMOSIS_DIR/bin/osmosis -q"


export OSMOSIS_DIR WORKDIR DATABASE USER PASS BOUNDING_BOX PREFIX OSMOSIS
